# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[kubernetes]
disabled = false
# format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
# format = '[$symbol$context( \($namespace\))]($style) in '

[[kubernetes.contexts]]
context_pattern = "kind-.*"
context_alias = "kind"
